# Generated by Django 2.2.2 on 2020-04-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingCheckApp', '0002_auto_20200402_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.AlterField(
            model_name='post',
            name='input_code',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='入力例'),
        ),
        migrations.AlterField(
            model_name='post',
            name='input_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力説明'),
        ),
        migrations.AlterField(
            model_name='post',
            name='output_code',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='出力例'),
        ),
        migrations.AlterField(
            model_name='post',
            name='output_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力説明'),
        ),
        migrations.AlterField(
            model_name='post',
            name='problem_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='問題文'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力サンプル1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力サンプル2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力サンプル3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力サンプル４'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='入力サンプル5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力サンプル1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力サンプル2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力サンプル3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output4',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力サンプル4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output5',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='出力サンプル5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
