# Generated by Django 2.1 on 2020-04-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingCheckApp', '0005_auto_20200411_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='method',
            field=models.CharField(choices=[('equality', '='), ('estimation', '<')], default='equality', max_length=20, verbose_name='判定基準'),
        ),
        migrations.AddField(
            model_name='post',
            name='tolerable_error',
            field=models.FloatField(blank=True, default=0, verbose_name='許容誤差'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitcode',
            name='file',
            field=models.FileField(upload_to='codes/2020-04-18', verbose_name='コード'),
        ),
    ]
