# Generated by Django 2.1 on 2020-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingCheckApp', '0007_auto_20200418_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitcode',
            name='file',
            field=models.FileField(upload_to='', verbose_name='コード'),
        ),
    ]
