# Generated by Django 2.1 on 2020-04-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingCheckApp', '0012_auto_20200425_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sample_input1',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='入力サンプル1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input2',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='入力サンプル2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input3',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='入力サンプル3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input4',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='入力サンプル４'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_input5',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='入力サンプル5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output1',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='出力サンプル1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output2',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='出力サンプル2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output3',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='出力サンプル3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output4',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='出力サンプル4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output5',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='出力サンプル5'),
        ),
    ]
